project_id = "mpgbcxdtmbvwrnqgebos"

[functions.matchmaking]
verify_jwt = false

[functions.api-metrics]
verify_jwt = false

[functions.ensure-room]
verify_jwt = false

[functions.chat-ai]
verify_jwt = false
